// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/author.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "article-service/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthorRepository is a mock of IAuthorRepository interface.
type MockIAuthorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthorRepositoryMockRecorder
}

// MockIAuthorRepositoryMockRecorder is the mock recorder for MockIAuthorRepository.
type MockIAuthorRepositoryMockRecorder struct {
	mock *MockIAuthorRepository
}

// NewMockIAuthorRepository creates a new mock instance.
func NewMockIAuthorRepository(ctrl *gomock.Controller) *MockIAuthorRepository {
	mock := &MockIAuthorRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthorRepository) EXPECT() *MockIAuthorRepositoryMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockIAuthorRepository) GetById(context context.Context, id int64) domain.Author {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", context, id)
	ret0, _ := ret[0].(domain.Author)
	return ret0
}

// GetById indicates an expected call of GetById.
func (mr *MockIAuthorRepositoryMockRecorder) GetById(context, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIAuthorRepository)(nil).GetById), context, id)
}
